Do not exit from dbench and iozone if patching fails
SVN revision 10053

diff --git a/test/automated/userint-tests.d/dbench b/test/automated/userint-tests.d/dbench
--- a/test/automated/userint-tests.d/dbench
+++ b/test/automated/userint-tests.d/dbench
@@ -37,12 +37,12 @@ then
 	#apply patches
 	patch -p3 < ${USERLIB_SCRIPTS}/dbench.patch
 
-	if [ "${?}" != 0 ]
-	then
-   		echo "Error: failed to apply patches to DBENCH."
-   		cd $cwd
-   		exit 1;
-	fi
+#	if [ "${?}" != 0 ]
+#	then
+ #  		echo "Error: failed to apply patches to DBENCH."
+  # 		cd $cwd
+   #		exit 1;
+#	fi
 
 	#compile the system
 	make 2>&1
diff --git a/test/automated/userint-tests.d/iozone b/test/automated/userint-tests.d/iozone
--- a/test/automated/userint-tests.d/iozone
+++ b/test/automated/userint-tests.d/iozone
@@ -6,11 +6,11 @@ cd ${EXTRA_TESTS}/iozone3_239/src/current  || exit 1
 if [ ! -f ./iozone ] 
 then
 patch -p5 < ${USERLIB_SCRIPTS}/iozone.patch
-	if [ $? != 0 ]
-	then
-   		echo "Attemp to patch iozone software failed."
-   		exit 1
-	fi
+	#if [ $? != 0 ]
+	#then
+   	#	echo "Attemp to patch iozone software failed."
+   	#	exit 1
+	#fi
 	make linux  || exit 1
 fi
 # -y min record size
