Check to see if dbench and iozone exist before trying to rebuild.
SVN revision 10049

diff --git a/test/automated/userint-tests.d/iozone b/test/automated/userint-tests.d/iozone
--- a/test/automated/userint-tests.d/iozone
+++ b/test/automated/userint-tests.d/iozone
@@ -1,13 +1,18 @@
 #!/bin/sh
 
 cd ${EXTRA_TESTS}/iozone3_239/src/current  || exit 1
-patch -p5 < ${USERLIB_SCRIPTS}/iozone.patch
-if [ $? != 0 ]
+
+#do we need to rebuild iozone
+if [ ! -f ./iozone ] 
 then
-   echo "Attemp to patch iozone software failed."
-   exit 1
+patch -p5 < ${USERLIB_SCRIPTS}/iozone.patch
+	if [ $? != 0 ]
+	then
+   		echo "Attemp to patch iozone software failed."
+   		exit 1
+	fi
+	make linux  || exit 1
 fi
-make linux  || exit 1
 # -y min record size
 # -q max record size
 # -n min file size
