aps: convert pvfs2-getmattr and pvfs2-setmattr from csh to bash.
    The debianization of orangefs pointed out that debian hates csh scripts.
    I guess because they're not POSIX, maybe other reasons too...

Signed-off-by: Mike Marshall <hubcap@omnibond.com>

diff --git a/src/apps/admin/pvfs2-getmattr b/src/apps/admin/pvfs2-getmattr
--- a/src/apps/admin/pvfs2-getmattr
+++ b/src/apps/admin/pvfs2-getmattr
@@ -1,99 +1,10 @@
-#!/bin/csh -f
-unalias *
+#!/bin/bash
+#
+# This script expects pvfs2-xattr and pvfs2-stat to be on your search path.
+#
 
-#set echo
-#set verbose
-
-#echo $0
-
-#if no options entered, then display usage information
-if ( $#argv == 0 ) then
-   goto usage
-endif
-
-#get the path associated with this command
-set mybin = $0:h
-
-#make sure that pvfs-xattr exists
-if ( ! -e $mybin/pvfs2-xattr ) then
-   echo
-   echo "$mybin/pvfs2-xattr command not found."
-endif
-
-#initialize parms
-set init = "init"
-set myFile = $init
-set myCopiesParm = 0
-set myModeParm   = 0
-set myFileParm   = 0
-
-#parse the command line....
-set index = 1
-set i
-while ( $index <= $#argv )
-
-   switch({$argv[$index]})
-   case {-h} :
-       goto usage
-       breaksw
-   case {-c} :
-       set myCopiesParm = 1
-       @ index++
-       breaksw
-   case {-m} :
-       set myModeParm = 1
-       @ index++
-       breaksw
-   case {-f} :
-       if ( $index == $#argv ) then
-          echo
-          echo "Missing file parameter.  Recheck usage."
-          goto usage
-       else
-          @ i = $index + 1
-          set myFileParm = 1
-          set myFile = $argv[$i]
-          @ index += 2
-       endif
-       breaksw
-   default :
-       echo
-       echo "Missing or invalid parameters.  Recheck usage."
-       goto usage
-       breaksw
-   endsw
-end #while
-
-
-#NOTE:  When PVFS is NOT in kernel mode, we can't easily check for file
-#       existence.  So, we just check to see that SOMETHING was entered.
-#       pvfs-xattr will validate the filename.
-#Did the user enter a file name?
-if ( $myFile == $init ) then
-   echo
-   echo "File name is required. Recheck usage."
-   goto usage
-endif
-
-#issue commands
-if ( $myCopiesParm && $myModeParm ) then
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.mode   -t {$myFile}
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.copies -t {$myFile}
-else if ( $myCopiesParm ) then
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.copies -t {$myFile}
-else if ( $myModeParm ) then
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.mode   -t {$myFile}
-else
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.mode   -t {$myFile}
-   {$mybin}/pvfs2-xattr -k user.pvfs2.mirror.copies -t {$myFile}
-endif
-
-#leave script
-exit
-
-#display help and exit script
-usage:
-    echo
+function usage {
+echo
     echo "pvfs2-getmattr [-c] [-m] [-h] -f file"
     echo "  -c : Retrieve the number of mirror copies"
     echo "  -m : Retrieve the mirroring mode"
@@ -101,5 +12,56 @@ usage:
     echo
     echo "Retrieve copies and mode when none specified.  File " \
          "is required."
-exit
-######## end of script file ##########
+    exit
+}
+
+if [ "$#" -lt 2 ] || [ "$#" -gt 4 ]
+then
+  usage
+fi
+
+XATTR_PATH=`which pvfs2-xattr 2> /dev/null`
+if [ $? -eq "1" ]
+then
+  echo "pvfs2-xattr command not found."
+  exit
+fi
+
+MODE=0
+COPY=0
+
+while [[ $# -gt 0 ]]
+do
+  case "$1" in
+    -c) COPY=1
+        shift;;
+    -m) MODE=1
+        shift;;
+    -f) shift
+        pvfs2-stat "$1" > /dev/null 2>&1
+        if [ "$?" != 0 ]
+        then
+          usage
+        fi
+        TARGET="$1"
+        shift;;
+     *) usage;;
+  esac
+done
+
+if [ "$MODE" -eq 0 ] && [ "$COPY" -eq 0 ]
+then
+  MODE=1
+  COPY=1
+fi
+
+if [ "$COPY" -eq "1" ]
+then
+     pvfs2-xattr -k user.pvfs2.mirror.copies -t "$TARGET"
+fi
+
+if [ "$MODE" -eq "1" ]
+then
+     pvfs2-xattr -k user.pvfs2.mirror.mode -t "$TARGET"
+fi
+
