at least send a trivial error message if pvfs2test.py fails before any individual tests are executed
SVN revision 3230

diff --git a/test/automated/SUBMIT.pbs.template b/test/automated/SUBMIT.pbs.template
--- a/test/automated/SUBMIT.pbs.template
+++ b/test/automated/SUBMIT.pbs.template
@@ -22,11 +22,15 @@ NODEFILE="nodes.conf"
 
 cat $PBS_NODEFILE>/home/USER/testing/DATE/work/$NODEFILE
 cd $PBS_O_WORKDIR
+email=`grep EMAIL $CONFIGFILE | cut -d "=" -f 2`
 
 mpdboot --rsh=rsh --file=$HOME/nightly/nodes.conf
 
-# TODO: send email if this doesn't work too!
+# run test harness, send email if it returns an error code
 ./pvfs2tests.py $CONFIGFILE $PAVCONFIG /home/USER/testing/DATE/work/$NODEFILE
+if [ $? != 0 ] ; then
+	echo "pvfs2tests.py failure." | mail -s "PVFS2 test: FAIL" "$email" 
+fi
 
 mpdallexit
 
