added in the first flow test program and modified to work with latest io description api; made several minor changes to the flow code along the way, added in a template flowprotocol (renamed from default flow protocol in old tree)
SVN revision 38

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2149,7 +2149,7 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-ac_config_files="$ac_config_files Makefile src/io/trove/module.mk src/io/trove/trove-handle-mgmt/module.mk src/io/trove/trove-dbpf/module.mk src/common/quickhash/module.mk src/common/quicklist/module.mk src/common/dotconf/module.mk src/common/id-generator/module.mk src/common/gossip/module.mk src/common/gen-locks/module.mk src/common/llist/module.mk src/io/bmi/module.mk src/io/bmi/bmi_tcp/module.mk src/io/description/module.mk src/io/flow/module.mk src/io/flow/flowproto-bmi-trove/module.mk test/io/trove/module.mk test/common/quicklist/module.mk test/common/id-generator/module.mk test/common/gossip/module.mk test/common/gen-locks/module.mk test/io/bmi/module.mk test/io/description/module.mk"
+ac_config_files="$ac_config_files Makefile src/io/trove/module.mk src/io/trove/trove-handle-mgmt/module.mk src/io/trove/trove-dbpf/module.mk src/common/quickhash/module.mk src/common/quicklist/module.mk src/common/dotconf/module.mk src/common/id-generator/module.mk src/common/gossip/module.mk src/common/gen-locks/module.mk src/common/llist/module.mk src/io/bmi/module.mk src/io/bmi/bmi_tcp/module.mk src/io/description/module.mk src/io/flow/module.mk src/io/flow/flowproto-bmi-trove/module.mk src/io/flow/flowproto-template/module.mk test/io/trove/module.mk test/common/quicklist/module.mk test/common/id-generator/module.mk test/common/gossip/module.mk test/common/gen-locks/module.mk test/io/bmi/module.mk test/io/description/module.mk test/io/flow/module.mk"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -2472,6 +2472,7 @@ do
   "src/io/description/module.mk" ) CONFIG_FILES="$CONFIG_FILES src/io/description/module.mk" ;;
   "src/io/flow/module.mk" ) CONFIG_FILES="$CONFIG_FILES src/io/flow/module.mk" ;;
   "src/io/flow/flowproto-bmi-trove/module.mk" ) CONFIG_FILES="$CONFIG_FILES src/io/flow/flowproto-bmi-trove/module.mk" ;;
+  "src/io/flow/flowproto-template/module.mk" ) CONFIG_FILES="$CONFIG_FILES src/io/flow/flowproto-template/module.mk" ;;
   "test/io/trove/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/io/trove/module.mk" ;;
   "test/common/quicklist/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/common/quicklist/module.mk" ;;
   "test/common/id-generator/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/common/id-generator/module.mk" ;;
@@ -2479,8 +2480,9 @@ do
   "test/common/gen-locks/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/common/gen-locks/module.mk" ;;
   "test/io/bmi/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/io/bmi/module.mk" ;;
   "test/io/description/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/io/description/module.mk" ;;
+  "test/io/flow/module.mk" ) CONFIG_FILES="$CONFIG_FILES test/io/flow/module.mk" ;;
   "pvfs2-config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS pvfs2-config.h" ;;
-  *) { { echo "$as_me:2483: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2485: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2699,7 +2701,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2702: creating $ac_file" >&5
+    { echo "$as_me:2704: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2717,7 +2719,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2720: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2722: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2730,7 +2732,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2733: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2735: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2791,7 +2793,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:2794: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:2796: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -2802,7 +2804,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2805: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2807: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2815,7 +2817,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2818: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2820: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2932,7 +2934,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:2935: $ac_file is unchanged" >&5
+      { echo "$as_me:2937: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
