[pcarns]: configure time test for prototype of setxattr: sometimes it has a const argument, sometimes it doesn't.
SVN revision 4624

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4570,6 +4570,74 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_XATTR 1
 _ACEOF
 
+	have_xattr=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	have_xattr=no
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+if test "x$have_xattr" = "xyes"; then
+      echo "$as_me:$LINENO: checking for const argument to setxattr function" >&5
+echo $ECHO_N "checking for const argument to setxattr function... $ECHO_C" >&6
+   tmp_cflags=$CFLAGS
+      CFLAGS="CFLAGS -Werror"
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	#define __KERNEL__
+	#include <linux/fs.h>
+	int pvfs2_setxattr(struct dentry *dentry, const char *name,
+	const void *value, size_t size, int flags) { return (0);};
+	static struct inode_operations in_op = {
+		.setxattr = pvfs2_setxattr
+	};
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SETXATTR_CONST_ARG 1
+_ACEOF
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -4579,6 +4647,8 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	CFLAGS=$tmp_cflags
+fi
 
 
 for ac_header in linux/posix_acl.h
