Includes reverse merges from trunk in addition, it includes fixes for readdir and readdirplus to have a variable length number of directory entries passed in from client-core using a trailer page (currently). However, there is nothing that prevents us from sharing those pages with the kernel using vmap and friends which is the next logical step. So client-core now does a readdir/readdirplus and writev's the trailer page (which is essentially an encoded version of the readdir/readdirplus response) to the kmod. The kernel module decodes that and copies it to the user-space app (which issued the getdents/getdents_plus system call) Added/edited the getdents.c test program in the test/posix sub directory to issue getdents/getdents64/getdents_plus/getdents64_plus system calls Also fixed a critical bug that was somehow never triggered in readdir if the buffer size provided by glibc/user was not sufficient enough and we advance the f_pos token beyond where we stopped.
SVN revision 5172

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6680,7 +6680,8 @@ fi;
 
 
 
-	NOSTDINCFLAGS="-nostdinc -isystem `$CC -print-file-name=include`"
+
+	NOSTDINCFLAGS="-Werror-implicit-function-declaration -nostdinc -isystem `$CC -print-file-name=include`"
 
 	CFLAGS="$USR_CFLAGS $NOSTDINCFLAGS -I$lk_src/include -I$lk_src/include/asm-i386/mach-generic -I$lk_src/include/asm-i386/mach-default -DKBUILD_STR(s)=#s -DKBUILD_BASENAME=KBUILD_STR(empty)  -DKBUILD_MODNAME=KBUILD_STR(empty)"
 
@@ -8338,10 +8339,8 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
-	echo "$as_me:$LINENO: checking for second arg type int in address_space_operations releasepage" >&5
+								echo "$as_me:$LINENO: checking for second arg type int in address_space_operations releasepage" >&5
 echo $ECHO_N "checking for second arg type int in address_space_operations releasepage... $ECHO_C" >&6
-	tmp_cflags=$CFLAGS
-	CFLAGS="$CFLAGS -Werror"
 	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8350,16 +8349,12 @@ cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
 	    #define __KERNEL__
-	    #include <linux/fs.h>
-	    extern int rp(struct page *page, int foo);
+	    #include <linux/buffer_head.h>
+	    extern int try_to_release_page(struct page *page, int gfp_mask);
 
 int
 main ()
 {
-
-	    struct address_space_operations aso = {
-		.releasepage = rp
-	    };
 
   ;
   return 0;
@@ -8403,12 +8398,9 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-	CFLAGS=$tmp_cflags
 
-	echo "$as_me:$LINENO: checking for int return in inode_operations follow_link" >&5
+			echo "$as_me:$LINENO: checking for int return in inode_operations follow_link" >&5
 echo $ECHO_N "checking for int return in inode_operations follow_link... $ECHO_C" >&6
-	tmp_cflags=$CFLAGS
-	CFLAGS="$CFLAGS -Werror"
 	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8418,15 +8410,12 @@ cat >>conftest.$ac_ext <<_ACEOF
 
 	    #define __KERNEL__
 	    #include <linux/fs.h>
-	    extern int fl(struct dentry *d, struct nameidata *n);
+	    extern int page_follow_link_light(struct dentry *,
+	                                      struct nameidata *);
 
 int
 main ()
 {
-
-	    struct inode_operations io = {
-		.follow_link = fl
-	    };
 
   ;
   return 0;
@@ -8470,7 +8459,6 @@ echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-	CFLAGS=$tmp_cflags
 
 	echo "$as_me:$LINENO: checking for compat_ioctl member in file_operations structure" >&5
 echo $ECHO_N "checking for compat_ioctl member in file_operations structure... $ECHO_C" >&6
@@ -11765,7 +11753,6 @@ fi
 
 
 
-
 for ac_func in strnlen
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -11863,14 +11850,6 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
 _ACEOF
- cat >>confdefs.h <<\_ACEOF
-#define _GNU_SOURCE 1
-_ACEOF
-
-       cat >>confdefs.h <<\_ACEOF
-#define HAVE_STRNLEN 1
-_ACEOF
-
 
 fi
 done
@@ -13421,6 +13400,66 @@ else
    echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+echo "$as_me:$LINENO: checking for GNU-style strerror_r" >&5
+echo $ECHO_N "checking for GNU-style strerror_r... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#include <string.h>
+	extern char *strerror_r();
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GNU_STRERROR_R 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
 for d in src/apps src/io src/common src/client src/kernel \
        doc src/apps/kernel test; do
