Change configure test for db stat function so that test for malloc function ptr and txnid are tested in order.
SVN revision 4362

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5279,9 +5279,10 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
     fi
 
+
     CFLAGS="$CFLAGS -Wall"
-        echo "$as_me:$LINENO: checking for txnid parameter to DB stat function" >&5
-echo $ECHO_N "checking for txnid parameter to DB stat function... $ECHO_C" >&6
+    echo "$as_me:$LINENO: checking for four-parameter DB stat" >&5
+echo $ECHO_N "checking for four-parameter DB stat... $ECHO_C" >&6
     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -5289,86 +5290,19 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-    #include <db.h>
+      #include <db.h>
+      #include <stdlib.h>
 
 int
 main ()
 {
 
-    int ret = 0;
-    DB *db = db;
-    DB_TXN *txnid = txnid;
-    u_int32_t flags = 0;
+      int ret = 0;
+      DB *db = db;
+      int dummy = 0;
+      u_int32_t flags = 0;
 
-    ret = db->stat(db, txnid, NULL, flags);
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_TXNID_PARAMETER_TO_DB_STAT 1
-_ACEOF
-
-    have_txnid_param_to_stat=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    have_txnid_param_to_stat=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-    CFLAGS=$oldcflags
-
-    if test "x$have_txnid_param_to_stat" = "xno" ; then
-
-        echo "$as_me:$LINENO: checking for four-parameter DB stat" >&5
-echo $ECHO_N "checking for four-parameter DB stat... $ECHO_C" >&6
-        cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-        #include <db.h>
-
-int
-main ()
-{
-
-        int ret;
-        DB *db;
-        u_int32_t flags;
-
-        ret = db->stat(db, NULL, NULL, flags);
+      ret = db->stat(db, &dummy, malloc, flags);
 
   ;
   return 0;
@@ -5402,15 +5336,87 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_UNKNOWN_PARAMETER_TO_DB_STAT 1
 _ACEOF
 
+    have_db_stat_malloc=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+    have_db_stat_malloc=no
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+        if test "x$have_txnid_param_to_stat" = "xno" ; then
+
+       echo "$as_me:$LINENO: checking for txnid parameter to DB stat function" >&5
+echo $ECHO_N "checking for txnid parameter to DB stat function... $ECHO_C" >&6
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+       #include <db.h>
+
+int
+main ()
+{
+
+       int ret = 0;
+       DB *db = db;
+       DB_TXN *txnid = txnid;
+       u_int32_t flags = 0;
+
+        ret = db->stat(db, txnid, NULL, flags);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TXNID_PARAMETER_TO_DB_STAT 1
+_ACEOF
+
+        have_txnid_param_to_stat=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        have_txnid_param_to_stat=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
     fi
+
+    CFLAGS=$oldcflags
 
         echo "$as_me:$LINENO: checking for txnid parameter to DB open function" >&5
 echo $ECHO_N "checking for txnid parameter to DB open function... $ECHO_C" >&6
