Fixing configure so that when with-db is set, we try to actually link against that version of db in configure tests.
SVN revision 4364

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5076,10 +5076,59 @@ if test "${with_db+set}" = set; then
   LDFLAGS="${LDFLAGS} -L$withval/lib" CFLAGS="${CFLAGS} -I$withval/include"
 fi;
 
-    echo "$as_me:$LINENO: checking for db library" >&5
+                        echo "$as_me:$LINENO: checking for db library" >&5
 echo $ECHO_N "checking for db library... $ECHO_C" >&6
     oldlibs=$LIBS
-    for lib in db4  db3  db  notfound; do
+    lib=notfound
+    if test "x$with_db_set" == "xyes" ; then
+        LIBS="${oldlibs} -ldb"
+        DB_LIB="-ldb"
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <db.h>
+int
+main ()
+{
+DB *dbp; db_create(&dbp, NULL, 0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  lib=db
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    else
+        for lib in db4  db3  db  notfound; do
            LIBS="${oldlibs} -l$lib"
            DB_LIB="-l$lib"
            cat >conftest.$ac_ext <<_ACEOF
@@ -5126,7 +5175,9 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-    done
+        done
+    fi
+
         LIBS=$oldlibs
     if test "x$lib" == "xnotfound" ; then
            { { echo "$as_me:$LINENO: error: could not find DB libraries" >&5
@@ -5279,10 +5330,9 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
     fi
 
-
     CFLAGS="$CFLAGS -Wall"
-    echo "$as_me:$LINENO: checking for four-parameter DB stat" >&5
-echo $ECHO_N "checking for four-parameter DB stat... $ECHO_C" >&6
+                            echo "$as_me:$LINENO: checking for DB stat with malloc function ptr" >&5
+echo $ECHO_N "checking for DB stat with malloc function ptr... $ECHO_C" >&6
     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -5347,7 +5397,7 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
-        if test "x$have_txnid_param_to_stat" = "xno" ; then
+        if test "x$have_db_stat_malloc" = "xno" ; then
 
        echo "$as_me:$LINENO: checking for txnid parameter to DB stat function" >&5
 echo $ECHO_N "checking for txnid parameter to DB stat function... $ECHO_C" >&6
