fix error message typo
SVN revision 5645

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5512,8 +5512,8 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-{ { echo "$as_me:$LINENO: error: Invalid openssl path specified.  No openssl/evp.h found." >&5
-echo "$as_me: error: Invalid openssl path specified.  No openssl/evp.h found." >&2;}
+{ { echo "$as_me:$LINENO: error: Invalid openssl path specified.  No openssl/bio.h found." >&5
+echo "$as_me: error: Invalid openssl path specified.  No openssl/bio.h found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
