SVN revision 9553

diff --git a/test/automated/vfs-tests.d/ltp b/test/automated/vfs-tests.d/ltp
--- a/test/automated/vfs-tests.d/ltp
+++ b/test/automated/vfs-tests.d/ltp
@@ -49,7 +49,12 @@ cd ltp-full-${LTPVER}
 #    exit 1;
 #fi
 echo Configuring LTP...
-./configure
+./configure >& /dev/null
+if [ "${?}" != 0 ]
+then
+    echo "Error: failed to configure LTP."
+    exit 1;
+fi
 echo Compiling LTP...
 export CFLAGS="-g"
 make all>& /dev/null 
