print all test failure messages to stderr
SVN revision 7683

diff --git a/test/automated/sysint-tests.d/misc b/test/automated/sysint-tests.d/misc
--- a/test/automated/sysint-tests.d/misc
+++ b/test/automated/sysint-tests.d/misc
@@ -6,7 +6,7 @@
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-touch $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-touch failure."
+    echo "pvfs2-touch failure." 1>&2
     exit 1
 fi
 
@@ -14,125 +14,126 @@ MYGROUP=`groups | cut -d ' ' -f 1`
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-chown $USER $MYGROUP $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-chown failure."
+    echo "pvfs2-chown failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-chmod 777 $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-chmod failure."
+    echo "pvfs2-chmod failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-drop-caches -m $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-drop-caches failure."
+    echo "pvfs2-drop-caches failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-fsck -m $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-fsck failure."
+    echo "pvfs2-fsck failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-validate -d $PVFS2_MOUNTPOINT -c -f -s
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-statfs failure."
+    echo "pvfs2-statfs failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-fs-dump -m $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-fs-dump failure."
+    echo "pvfs2-fs-dump failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-fs-dump -m $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-fs-dump failure."
+    echo "pvfs2-fs-dump failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-ls $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-ls failure."
+    echo "pvfs2-ls failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-perror 0 
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-perror failure."
+    echo "pvfs2-perror failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-stat $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-stat failure."
+    echo "pvfs2-stat failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-viewdist -f $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-viewdist failure."
+    echo "pvfs2-viewdist failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-xattr -s -k user.foo -v bar $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-xattr failure."
+    echo "pvfs2-xattr failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-rm $PVFS2_MOUNTPOINT/miscfile
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-rm failure."
+    echo "pvfs2-rm failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-set-debugmask -m $PVFS2_MOUNTPOINT "none"
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-set-debugmask failure."
+    echo "pvfs2-set-debugmask failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-set-mode -m $PVFS2_MOUNTPOINT "admin"
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-set-mode failure." exit 1
+    echo "pvfs2-set-mode failure."  1>&2
+    exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-set-mode -m $PVFS2_MOUNTPOINT "normal"
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-set-mode failure."
+    echo "pvfs2-set-mode failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-set-sync -m $PVFS2_MOUNTPOINT -D 0 -M 1
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-set-sync failure."
+    echo "pvfs2-set-sync failure." 1>&2
     exit 1
 fi
 
 ${PVFS2_DEST}/INSTALL-pvfs2-${CVS_TAG}/bin/pvfs2-statfs -m $PVFS2_MOUNTPOINT
 if [ "${?}" != 0 ]
 then
-    echo "pvfs2-statfs failure."
+    echo "pvfs2-statfs failure." 1>&2
     exit 1
 fi
 
