Fixed problem with tests hanging. Also added update feature
SVN revision 9660

diff --git a/test/scripts/runalltests b/test/scripts/runalltests
--- a/test/scripts/runalltests
+++ b/test/scripts/runalltests
@@ -6,6 +6,7 @@
 
 
 DATE=`date +'%Y%m%d'`
+DATETIME=`date +'%Y%m%d-%H.%M.%S'`
 #export VMUSER=ec2-user
 VMUSER=ubuntu
 #export VMSYSTEM=sl6-mpi
@@ -126,7 +127,7 @@ euca-describe-keypairs --config=${EC2CONFFILE} --filter key-name=$KEYNAME
 
 if [ $? != 0 ]
 then
-	echo "Keyname $KEYNAME not found in EC2"
+	echo "Keyname $KEYNAME not found."
 	exit 1
 fi
 
@@ -143,16 +144,32 @@ then
 	echo "Generating new instance of $VMSYSTEM"
 	echo "euca-run-instances -n 1 --config ${EC2CONFFILE} --debug -k $KEYNAME -t m1.medium $VMSYSTEM > newinstance.out 2> newinstance.err"
 
-	euca-run-instances -n 1 --config ${EC2CONFFILE} --debug -k $KEYNAME -t m1.medium $VMSYSTEM > newinstance.out 2> newinstance.err || exit 1
+	euca-run-instances -n 1 --config ${EC2CONFFILE} --debug -k $KEYNAME -t m1.medium $VMSYSTEM > newinstance.out 2> newinstance.err 
 
+	if [ $? -ne 0 ]
+	then
+		echo "Could not create instance of $VMSYSTEM. Exiting"
+		exit 1
+	fi
+	
 	VMINSTANCEID=`cat newinstance.out | grep INSTANCE | awk '{print $2}'`
 
-	echo "VM Instance id is ${VMINSTANCEID}"
-	#wait 30 seconds to start instance
-	sleep 30
+	echo "VM Instance of $VMSYSTEM created. Instance id is ${VMINSTANCEID}"
+	#wait 20 seconds to start instance
+	sleep 20
 
+	RUNNING=`euca-describe-instances instance-id=${VMINSTANCEID} --config ${EC2CONFFILE} | grep INSTANCE | awk '{ print $6 }'`
+	
+	until [ "$RUNNING" == "running" ]
+	do
+		RUNNING=`euca-describe-instances instance-id=${VMINSTANCEID} --config ${EC2CONFFILE} | grep INSTANCE | awk '{ print $6 }'`
+		sleep 10
+		echo "Instance ${VMINSTANCEID} is ${RUNNING}"
+	done
+	
+	#Now grab the IP Address of the new instance
 	VMIPADDR=`euca-describe-instances instance-id=${VMINSTANCEID} --config ${EC2CONFFILE} | grep INSTANCE | awk '{ print $13 }'`
-	sleep 30
+	
 fi
 
 echo "VM IP ADDRESS is ${VMIPADDR}"
@@ -163,31 +180,56 @@ echo "VM IP ADDRESS is ${VMIPADDR}"
 
 #need to make sure key can import itself automatically
 
-ssh-keygen -f "~/.ssh/known_hosts" -R ${VMIPADDR}
+echo "Removing obsolete ssh host records at ~/.ssh/known_hosts for new instance."
+ssh-keygen -f ~/.ssh/known_hosts -R ${VMIPADDR}
+
+ssh -i $KEYFILE ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no true
+
+#is SSH responding?
+until [ $? -eq 0 ]
+do
+	sleep 10
+	ssh -i $KEYFILE ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no true
+done
+
+#rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./update-${VMSYSTEM}.sh ${VMUSER}@${VMIPADDR}:/home/${VMUSER}
+#ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "/home/${VMUSER}/update-${VMSYSTEM}.sh" 
+ssh -i ${KEYFILE} -t ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'bash -s' < update-${VMSYSTEM}.sh 
+
+echo "Waiting for image to reboot..."
+sleep 20
+
+ssh -i $KEYFILE ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no true
+
+#is SSH responding?
+until [ $? -eq 0 ]
+do
+	sleep 10
+	ssh -i $KEYFILE ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no true
+done
 
 
-#prepare the image for testing
-ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'bash -s' < prepare-${VMSYSTEM}.sh || exit 1
+ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'echo System rebooted. Test system is `uname -a`' 
 
-#run the test
-#echo ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'bash -s' < ./run-test.sh ${SVNBRANCH}
-ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'cat | bash /dev/stdin' "${SVNBRANCH}" < ./run-test.sh || exit 1
+echo "Prepare the image for testing..."
+ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'bash -s' < prepare-${VMSYSTEM}.sh 
 
-#grab the logs
-rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${VMUSER}@${VMIPADDR}:/tmp/${VMUSER}/pvfs2-nightly/${DATE}/${SVNBRANCH}/*.log logs || exit 1
+echo "Running tests..."
+ssh -i ${KEYFILE} ${VMUSER}@${VMIPADDR} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "RUN_VFS_TEST=${RUN_VFS_TEST} RUN_MPI_TEST=${RUN_MPI_TEST} SVNBRANCH=${SVNBRANCH} bash -s " < ./run-test.sh 
 
-#grab the scripts
-rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${VMUSER}@${VMIPADDR}:/home/${VMUSER}/*.txt scripts || exit 1
-
+echo "Grabbing logs and scripts from server"
+rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${VMUSER}@${VMIPADDR}:/tmp/${VMUSER}/pvfs2-nightly/${DATE}/${SVNBRANCH}/*.log logs-$DATETIME/
+rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${VMUSER}@${VMIPADDR}:/home/${VMUSER}/*.txt logs-$DATETIME/
+rsync -a -e "ssh -i ${KEYFILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${VMUSER}@${VMIPADDR}:/home/${VMUSER}/*.out logs-$DATETIME/
  
-#process the logs 
+echo "Process the logs" 
 SVNBRANCH_SHORT=`echo $SVNBRANCH | awk -F"/" '{print $NF}'`
-./checklogs.pl "`pwd`/logs/alltests-${SVNBRANCH_SHORT}.log"
+./checklogs.pl "`pwd`/logs-$DATETIME/alltests-${SVNBRANCH_SHORT}.log"
 
 if [ $? -ne 0 ]
 then
 	#if the log check failed, bailout before deleteing instance
-	echo "Some tests failed. Please check `pwd`/logs/alltests-$SVNBRANCH_SHORT for more details."
+	echo "Some tests failed. Please check `pwd`/logs-$DATETIME/alltests-$SVNBRANCH_SHORT for more details."
 	echo "Instance $VMINSTANCEID at $VMIPADDR NOT deleted."
 	exit 1
 fi
